### ISSUE TITLE
変数名は中身がわかるようにつける

### ISSUE THREAD

**Issue by norotime** [iceicicle/project#1]
https://github.com/iceicicle/project/blob/e86258d02c2d3811c1596903d7196f63a7ea7a96/app/controllers/tweets_controller.rb#L3

@iceicicle .allで取得した時は、複数のデータが格納される可能性があるため複数形。
.newの時は一つのデータのみのはずなので単数形にしましょう。
_ivewや _createとつける必要はないですよーー。
逆につけていると？？となります。

**Comment by iceicicle** [comment]
学習を進めていく上で、すべて同じ変数名にすると、index.html、new.html、edit.htmlでどのコントローラのどの変数を見ているのか混乱してしまったのが原因です…
処理の流れを追う上で非常に役立ちましたが、裏を返せば、それさえ分かれば分ける必要はなさそうですね…
ご指摘通り修正いたします。
