### ISSUE TITLE
文字列表記よりもシンボル表記の方が高速なため書き換える

### ISSUE THREAD

**Issue by norotime** [iceicicle/project#2]
https://github.com/iceicicle/project/blob/e86258d02c2d3811c1596903d7196f63a7ea7a96/app/controllers/tweets_controller.rb#L16

**Comment by norotime** [comment]
@iceicicle シンボルを使うメリットは下記です。

```
新しく文字列を生成しない分やや効率がよく、比較も高速。
文字の意味がはっきりするのでコードが読みやすくなる
immutable なので内容を書き換えられる心配がない
```

**Comment by iceicicle** [comment]
シンボルというと、ハッシュを扱うときによく使われるイメージですが、ここで文字列表記からシンボル表記に変更できる理由は、内部的にハッシュを扱っているのでしょうか……
やや疑問が残るものの、先にクローズしておきます。
