### ISSUE TITLE
利用していないヘルパーファイルはファイルごと削除する

### ISSUE THREAD

**Issue by norotime** [iceicicle/project#3]
https://github.com/iceicicle/project/blob/e86258d02c2d3811c1596903d7196f63a7ea7a96/app/helpers/tweets_helper.rb#L1

**Comment by iceicicle** [comment]
今回は、確認画面を省略しており、アクションによって処理を分岐させる必要がないため、ヘルパーメソッドが不必要となったんですね…
半分以上自分に言い聞かせながら、削除いたします。
